# Projected coordinate system to use for metric operations (e.g., computing edges' length).
# See: https://en.wikipedia.org/wiki/Projected_coordinate_system
crs = "EPSG:2154"

# Path to the file where the imported edges are stored
# (possible extensions: parquet, geojson, fgb, shp).
raw_edges_file = "./output/edges.parquet"
# Path to the file where the imported edges are stored after the cleaning process
# (possible extensions: parquet, geojson, fgb, shp).
clean_edges_file = "./output/edges_clean.parquet"

[metropolis]
# Directory where the run input files should be stored.
input_directory = "./run/"
# Format to use for the input and output files ("CSV" or "Parquet").
format = "Parquet"

# Constant time penalty, in seconds, added to the edges' travel times.
# For now, it is limited to the function of the `target_count` of edges (i.e., the number of
# incoming edges for the edge's target node).
# The `default` value is used if there is no specified value for a given edge's `target_count`.
[metropolis.travel_time_penalties]
1 = 0.0
2 = 3.0
3 = 4.0
default = 5.0

[osm]
# Path to the .osm.pbf file to use as input.
input_file = "./data/corse-latest.osm.pbf"
# OpenStreetMap's highway tags to import.
# See https://wiki.openstreetmap.org/wiki/Key:highway
highways = [
  "motorway",
  "trunk",
  "primary",
  "secondary",
  "tertiary",
  "motorway_link",
  "trunk_link",
  "primary_link",
  "secondary_link",
  "tertiary_link",
  "living_street",
  "unclassified",
  "residential",
  #"road",
  #"service",
]
# Array of OpenStreetMap's landuse tags to be considered as urban areas.
# See https://wiki.openstreetmap.org/wiki/Key:landuse
urban_landuse = [
  "commercial",
  "construction",
  "education",
  "industrial",
  "residential",
  "retail",
  #"grass",
  #"cemetery",
  #"basin",
  #"allotments",
  "village_green",
  #"flowerbed",
  "recreation_ground",
  "military",
  "garages",
  "religious"
]


[postprocess_network]
# Minimum number of lanes allowed on edges.
min_nb_lanes = 0.5
# Minimum speed allowed on edges (in km/h).
min_speed = 10
# Minimum length allowed on edges (in meters).
min_length = 1
# Whether the network should be restricted to the largest strongly connected component of the
# underlying graph.
# Warning. If `false`, some origin-destination pairs might not be feasible.
ensure_connected = true

# Default speed per roadtype, in km/h, in rural areas.
[postprocess_network.default_speed.rural]
motorway = 130
trunk = 110
primary = 80
secondary = 80
tertiary = 80
motorway_link = 90
trunk_link = 70
primary_link = 50
secondary_link = 50
tertiary_link = 50
living_street = 20
unclassified = 20
residential = 30
#road = 20
#service = 20

# Default speed per roadtype, in km/h, in urban areas.
[postprocess_network.default_speed.urban]
motorway = 130
trunk = 110
primary = 50
secondary = 50
tertiary = 50
motorway_link = 90
trunk_link = 70
primary_link = 50
secondary_link = 50
tertiary_link = 50
living_street = 20
unclassified = 20
residential = 30
#road = 20
#service = 20

# Default number of lanes per roadtype.
[postprocess_network.default_nb_lanes]
motorway = 2
trunk = 2
primary = 1
secondary = 1
tertiary = 1
motorway_link = 1
trunk_link = 1
primary_link = 1
secondary_link = 1
tertiary_link = 1
living_street = 1
unclassified = 1
residential = 1
#road = 1
#service = 1

# Default bottleneck capacity per roadtype, in PCE/h.
[postprocess_network.default_capacity]
motorway = 2000
trunk = 2000
primary = 1500
secondary = 800
tertiary = 600
motorway_link = 1500
trunk_link = 1500
primary_link = 1500
secondary_link = 800
tertiary_link = 600
living_street = 300
unclassified = 600
residential = 600
#road = 300
#service = 300
