name: metropolis-roadnetwork
channels:
  - conda-forge
dependencies:
  - geopandas=0.14.3
  - networkx=3.2.1
  - numpy=1.26.4
  - pandas=2.2.1
  - pip=24.0
  - polars=0.20.16
  - pyarrow=15.0.2
  - python=3.12.2
  - pip:
      - osmium==3.7.0
